services:
  postgres-schrottdaten:
    image: postgres:latest
    container_name: schrottdaten-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schrottdaten
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    restart: always