services:
  postgres:
    image: postgres:latest
    container_name: schrottdaten-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: herne
      POSTGRES_PASSWORD: herne
      POSTGRES_DB: schrottdaten
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d