name: swt2-sose2025
services:

  # Spring Boot App für Schrottdaten
  schrottdaten:
    build: schrottdaten
    container_name: schrottdaten-app
    depends_on:
      - postgres
      - broker
      - schrottverwaltung
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/schrottdaten
      SPRING_DATASOURCE_USERNAME: herne
      SPRING_DATASOURCE_PASSWORD: herne
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

  # Verwaltungskomponente, ggf. zweite App
  schrottverwaltung:
    build: schrottverwaltung
    container_name: schrottverwaltung-app
    depends_on:
      - postgres-schrottverwaltung
      - broker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-schrottverwaltung:5432/schrottverwaltung
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

  # Eclipse Mosquitto
  broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883" #MQTT Standart Port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

#  schrottportal:
#      build: ./schrottportal
#      container_name: schrottportal-frontend
#      ports:
#        - "4200:4200"
#      restart: always

  # Zweite PostgreSQL-DB für Schrottverwaltung
  postgres-schrottverwaltung:
    image: postgres:latest
    container_name: schrottverwaltung-db
    environment:
      POSTGRES_DB: schrottverwaltung
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - ./dataset/schrottverwaltung:/docker-entrypoint-initdb.d
    restart: always

  # Hauptdatenbank für Schrottdaten
  postgres:
    image: postgres:latest
    container_name: schrottdaten-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: schrottdaten
      POSTGRES_USER: herne
      POSTGRES_PASSWORD: herne
    volumes:
      - ./dataset/schrottdaten:/docker-entrypoint-initdb.d
