services:
  postgres-schrottverwaltung:
    image: postgres:latest
    container_name: schrottverwaltung-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    restart: always