services:
  postgres-schrottverwaltung:
    image: postgres:latest
    container_name: schrottverwaltung-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pg_data_schrottverwaltung:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data_schrottverwaltung: