name: Pre Merge Checks

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [24]
        project:
          - schrottverwaltung
          - schrottdaten
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "temurin"
          cache: gradle
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with gradle of ${{ matrix.project }}
        if: ${{ matrix.project != '' }}
        working-directory: ${{ matrix.project }}
        run: ./gradlew check
