name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        project:
          -
            # This is a list of all projects that should be built and pushed.
            # YOU NEED TO UPDATE THIS LIST WHEN YOU ADD A NEW PROJECT AND WITH
            # THE CORRECT NAME OF THE PROJECT FOLDER.
            # - project_one
          # - project_two
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Container Metadata
        id: metadata
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ matrix.project }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: lower-repo
        name: Convert name of repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: ${{ matrix.project != '' }}
        with:
          context: ${{ matrix.project }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.lower-repo.outputs.repository }}/${{ matrix.project }}:${{ github.sha }}
          labels: ${{ steps.metadata.outputs.labels }}
